### PR TITLE
Update Controller.py

### PR DESCRIPTION
**Pull request by SteamsDev**
This should be the final update before we reach 100% (or nearly 100%) test coverage.

### CODE REVIEW

**Review by tmhughes1 — APPROVED** [review]

**Review by auanmu — APPROVED** [review]
looks good, ty for changing.

**Review by tmhughes1 — CHANGES_REQUESTED** [review]
don't comment out the model lines just delete them!

**Comment by SteamsDev** [comment]
That was a leftover from testing. Sorry.

**Review by auanmu — APPROVED** [review]

**Review by tmhughes1 — APPROVED** [review]
Thank you!

**Pull request merged**
