### PR TITLE
Redundant code refactor

### PR DESCRIPTION
**Pull request by auanmu**
Refactored point system, and how the pangram is pulled for base

### CODE REVIEW

**Review by SteamsDev — DISMISSED** [review]
Looks good!

**Review by tmhughes1 — CHANGES_REQUESTED** [review]
Absolutely no documentation !!! I'd like to see comments that explain the code so reviewers can read them as they go along and know exactly what your code is doing. Please add this!

**Comment by auanmu** [comment]
added documentation for identifybaseword.py

**Review by tmhughes1 — APPROVED** [review]

**Review by SteamsDev — APPROVED** [review]
Looks good!

**Pull request merged**
