### PR TITLE
Highscore fix

### PR DESCRIPTION
**Pull request by gabe2762**
tweaked some of the naming and comments (may have missed some so if I did just please point them out). All commented out code from me should be removed. Keeping in some test code to aid with debugging for now, but nothing is test code in the model, only in the CLI (which I'm not actually pushing yet) and the Highscores.py file

### CODE REVIEW

**Review by SteamsDev — APPROVED** [review]
Thanks Gabe! I'll have to try this out then.

**Review by tmhughes1 — CHANGES_REQUESTED** [review]
Why are you changing our core game run functions to return game_id? Does this affect our program at all? Why is it necessary? Also the comments for functions are still not the proper format, we use ''' ''' code segments not multiple #'s.

**Comment by gabe2762** [comment]
changing the controllerRunAutoGame and Base functions in controller was necessary since you didn't want me to use a getter method in the model. The only difference is that it stores and returns the game_id from the method in the model code, which is carried over into the CLI (which is where I have been setting it up so far) from the controllerRunAutoGame and Base functions. The NewPuzzleHelper method simply updates the lines where those are called like this: self.game_id = self.controller.controllerRunAutoGame() (and for the other one). This allows me to access the game_id while in the CLI file. It does not change any functionality and everything still works the same way, it was simply my workaround for not using a getter method. As for the comments, I will fix those and update this.

**Comment by tmhughes1** [comment]
My bad, it is actually okay to have the getter in the model like the rest of them! Just was thinking about test coverage but I'm sure Devon's got that covered. You can revert it back to how you had it

**Review by tmhughes1 — APPROVED** [review]
Thanks for making changes.

**Review by auanmu — APPROVED** [review]
Looks fine, path seems to be set correctly and connecting to the DB seems to be working from looking at the code.

**Pull request merged**
